### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by cckz** [ant-design/ant-design-colors#77]
hi, bundle crashes after last update
```
Documents\projects\sed_flexible_reports\node_modules\@ctrl\tinycolor\dist\module\conversion.js:1
import { bound01, pad2 } from './util';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1071:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (Documents\projects\sed_flexible_reports\node_modules\@ant-design\colors\dist\index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (Documents\projects\sed_flexible_reports\node_modules\@ant-design\icons\lib\utils.js:22:15)
    ```

**Comment by peterwiebe** [comment]
I also ran into this problem. I am able to fix it by going into _node_modules/@ant-design/colors/dis/index.js_ and changing
```js
var conversion = require('@ctrl/tinycolor/dist/module/conversion');
var formatInput = require('@ctrl/tinycolor/dist/module/format-input');
```

to this
```js
var conversion = require('@ctrl/tinycolor/dist/conversion');
var formatInput = require('@ctrl/tinycolor/dist/format-input');
```

**Comment by peterwiebe** [comment]
or for a more semi-permanent fix until a new release is published is to add the following to package.json until the breaking change is fixed (if you use yarn):
```json
"resolutions": {
  "@ant-design/colors": "5.0.0"
}
```

**Comment by jamsinclair** [comment]
/cc @zombieJ @07akioni 

For a quick summary, this breaking change was caused by tree shaking code being included in v5.1.0.

Looks like @zombieJ has fixed this in https://github.com/ant-design/ant-design-colors/pull/75. A new patch release with that commit will resolve this for everyone.

Appreciate the work you all do on this 😸 , many thanks!

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design-colors/commit/0f15e9570ce34a6499229f2ae9312be8c9696758

**Comment by zhangyuheng** [comment]
pro-layout is using `"@ant-design/icons": "^4.0.0",`

```
yarn why @ctrl/tinycolor
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@ctrl/tinycolor"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@ctrl/tinycolor@3.4.0"
info Reasons this module exists
   - "@ant-design#pro-layout#@ant-design#icons#@ant-design#colors" depends on it
   - Hoisted from "@ant-design#pro-layout#@ant-design#icons#@ant-design#colors#@ctrl#tinycolor"
info Disk size without dependencies: "344KB"
info Disk size with unique dependencies: "344KB"
info Disk size with transitive dependencies: "344KB"
info Number of shared dependencies: 0
✨  Done in 0.79s.
```

**Comment by jamsinclair** [comment]
@zombieJ thanks for the quick fix 🙌 . Anything blocking publishing v5.1.1 to npm? 🙏

**Comment by iamricky** [comment]
@cckz are you using Next.js?
